### ISSUE TITLE
Tip: When creating widget for an app, add this!

### ISSUE THREAD

**Issue by rayliverified** [obaro/SimpleAndroidWidget#1]
The tutorial at Android Authority had me stumped a bit as it did not work. When building a widget into an existing app, it is necessary to add a few lines to the receiver declaration. Add an icon and label to the tag for the widget to appear! 

`android:icon="@drawable/icon"
 android:label="Example Widget"`

Hope this helps!

**Comment by obaro** [comment]
Great tip @searchy2. Thanks.
